package workflow

import (
	"fmt"
	"time"

	"go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/workflow"

	"github.com/titlis/prbot/internal/activity"
	"github.com/titlis/prbot/internal/model"
)

type EnvDeploySpec struct {
	CampaignID        string
	TenantID          int64
	WorkloadUID       string
	WorkloadName      string
	Namespace         string
	RepoURL           string
	BaseBranch        string
	Env               model.EnvShort
	ManifestPath      string
	BranchName        string
	Recommendation    model.HpaRecommendation
	PolicyMode        model.PolicyMode
	MaxDeltaPct       int
	TriggerSource     model.TriggerSource
	// PrePatchedContent, when non-empty, skips FetchManifest+ApplyPatch and uses
	// this content directly. ValidatePatch still runs against the current file.
	PrePatchedContent []byte
	CommitMessage     string
	PRTitle           string
	PRBody            string
}

type EnvDeployResult struct {
	Status   model.EnvStepStatus
	PRNumber int
	PRURL    string
	Branch   string
	Reason   string
}

func defaultActivityOptions() workflow.ActivityOptions {
	return workflow.ActivityOptions{
		StartToCloseTimeout: 2 * time.Minute,
		RetryPolicy: &temporal.RetryPolicy{
			InitialInterval:    time.Second,
			BackoffCoefficient: 2.0,
			MaximumInterval:    time.Minute,
			MaximumAttempts:    5,
		},
	}
}

// notifyActivityOptions are used for fire-and-forget notification activities.
// A single attempt with a short timeout — failures are silently skipped.
func notifyActivityOptions() workflow.ActivityOptions {
	return workflow.ActivityOptions{
		StartToCloseTimeout: 15 * time.Second,
		RetryPolicy: &temporal.RetryPolicy{
			MaximumAttempts: 1,
		},
	}
}

func EnvDeployWorkflow(ctx workflow.Context, spec EnvDeploySpec) (EnvDeployResult, error) {
	ctx = workflow.WithActivityOptions(ctx, defaultActivityOptions())
	var a *activity.Activities

	// Idempotency: reuse open PR if branch was already pushed in a prior run.
	var existingPR activity.PROutput
	findErr := workflow.ExecuteActivity(ctx, a.FindOpenPR, activity.FindOpenPRInput{
		TenantID: spec.TenantID, RepoURL: spec.RepoURL, HeadBranch: spec.BranchName,
	}).Get(ctx, &existingPR)
	if findErr == nil && existingPR.Number > 0 {
		return EnvDeployResult{
			Status:   model.EnvStepPROpen,
			PRNumber: existingPR.Number,
			PRURL:    existingPR.URL,
			Branch:   existingPR.Branch,
			Reason:   "reused_existing_pr",
		}, nil
	}

	var current activity.FileContent
	if err := workflow.ExecuteActivity(ctx, a.FetchManifest, activity.FetchManifestInput{
		TenantID: spec.TenantID, RepoURL: spec.RepoURL, Branch: spec.BaseBranch, Path: spec.ManifestPath,
	}).Get(ctx, &current); err != nil {
		return EnvDeployResult{Status: model.EnvStepFailed, Reason: fmt.Sprintf("fetch: %v", err)}, nil
	}

	var patched []byte
	if len(spec.PrePatchedContent) > 0 {
		patched = spec.PrePatchedContent
	} else {
		if err := workflow.ExecuteActivity(ctx, a.ApplyPatch, activity.ApplyPatchInput{
			Current: current.Content, Recommendation: spec.Recommendation,
		}).Get(ctx, &patched); err != nil {
			return EnvDeployResult{Status: model.EnvStepFailed, Reason: fmt.Sprintf("patch: %v", err)}, nil
		}
	}

	var ok bool
	if err := workflow.ExecuteActivity(ctx, a.ValidatePatch, activity.ValidatePatchInput{
		Current: current.Content, New: patched,
	}).Get(ctx, &ok); err != nil {
		return EnvDeployResult{Status: model.EnvStepFailed, Reason: fmt.Sprintf("validate: %v", err)}, nil
	}

	if err := workflow.ExecuteActivity(ctx, a.CreateBranch, activity.BranchInput{
		TenantID: spec.TenantID, RepoURL: spec.RepoURL, BaseBranch: spec.BaseBranch, NewBranch: spec.BranchName,
	}).Get(ctx, nil); err != nil {
		return EnvDeployResult{Status: model.EnvStepFailed, Reason: fmt.Sprintf("branch: %v", err)}, nil
	}

	commitMsg := spec.CommitMessage
	if commitMsg == "" {
		commitMsg = fmt.Sprintf("titlis-prbot: HPA tuning (%s) for %s", spec.Env, spec.WorkloadName)
	}
	if err := workflow.ExecuteActivity(ctx, a.CommitFile, activity.CommitInput{
		TenantID: spec.TenantID, RepoURL: spec.RepoURL, Branch: spec.BranchName,
		Path: spec.ManifestPath,
		Message: commitMsg,
		Content: patched,
	}).Get(ctx, nil); err != nil {
		return EnvDeployResult{Status: model.EnvStepFailed, Reason: fmt.Sprintf("commit: %v", err)}, nil
	}

	title := spec.PRTitle
	if title == "" {
		title = fmt.Sprintf("Titlis: HPA tuning for %s (%s)", spec.WorkloadName, spec.Env)
	}
	body := spec.PRBody
	if body == "" {
		body = fmt.Sprintf("Recommendation source: %s\nConfidence: %.2f\n\nGenerated by titlis-prbot.",
			spec.Recommendation.Source, spec.Recommendation.Confidence)
	}
	var pr activity.PROutput
	if err := workflow.ExecuteActivity(ctx, a.OpenPR, activity.OpenPRInput{
		TenantID: spec.TenantID, RepoURL: spec.RepoURL,
		BaseBranch: spec.BaseBranch, HeadBranch: spec.BranchName,
		Title: title, Body: body, Labels: []string{"titlis/prbot"},
	}).Get(ctx, &pr); err != nil {
		return EnvDeployResult{Status: model.EnvStepFailed, Reason: fmt.Sprintf("open_pr: %v", err)}, nil
	}

	_ = workflow.ExecuteActivity(ctx, a.Notify, activity.NotifyInput{
		EventType: "remediation_started",
		TenantID:  spec.TenantID,
		Data: map[string]any{
			"workload_id":            spec.WorkloadUID,
			"campaign_id":            spec.CampaignID,
			"environment":            string(spec.Env),
			"github_pr_number":       pr.Number,
			"github_pr_url":          pr.URL,
			"github_branch":          pr.Branch,
			"repository_url":         spec.RepoURL,
			"status":                 "IN_PROGRESS",
			"recommendation_source":  spec.Recommendation.Source,
			"recommendation_conf":    spec.Recommendation.Confidence,
			"trigger_source":         string(spec.TriggerSource),
		},
	}).Get(ctx, nil)

	if spec.PolicyMode != model.PolicyAutoMerge {
		return EnvDeployResult{
			Status:   model.EnvStepPROpen,
			PRNumber: pr.Number, PRURL: pr.URL, Branch: pr.Branch,
		}, nil
	}

	var checks activity.WaitChecksOutput
	if err := workflow.ExecuteActivity(ctx, a.WaitChecks, activity.WaitChecksInput{
		TenantID: spec.TenantID, RepoURL: spec.RepoURL, PRNumber: pr.Number,
	}).Get(ctx, &checks); err != nil {
		return EnvDeployResult{Status: model.EnvStepAwaitingHuman, PRNumber: pr.Number, PRURL: pr.URL, Reason: "checks_error"}, nil
	}
	if checks.Status != "success" {
		return EnvDeployResult{Status: model.EnvStepAwaitingHuman, PRNumber: pr.Number, PRURL: pr.URL, Reason: "checks_not_green:" + checks.Status}, nil
	}

	if err := workflow.ExecuteActivity(ctx, a.MergePR, activity.MergePRInput{
		TenantID: spec.TenantID, RepoURL: spec.RepoURL, PRNumber: pr.Number, Method: "squash",
	}).Get(ctx, nil); err != nil {
		return EnvDeployResult{Status: model.EnvStepAwaitingHuman, PRNumber: pr.Number, PRURL: pr.URL, Reason: fmt.Sprintf("merge: %v", err)}, nil
	}

	_ = workflow.ExecuteActivity(ctx, a.Notify, activity.NotifyInput{
		EventType: "remediation_updated",
		TenantID:  spec.TenantID,
		Data: map[string]any{
			"workload_id":      spec.WorkloadUID,
			"campaign_id":      spec.CampaignID,
			"environment":      string(spec.Env),
			"github_pr_number": pr.Number,
			"status":           "COMPLETED",
		},
	}).Get(ctx, nil)

	return EnvDeployResult{Status: model.EnvStepMerged, PRNumber: pr.Number, PRURL: pr.URL, Branch: pr.Branch}, nil
}
